#!/usr/bin/env python
# Copyright 2016 LasLabs Inc.
# License Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0.html).

# This script will test that EXPECT is in the output from COMMAND

import os
import subprocess

COMMAND="openssl"
EXPECT="OpenSSL> "

cmd = 'docker exec -i -t %s %s' % (
    os.environ.get('DOCKER_CONTAINER_ID'),
    COMMAND
)

result = subprocess.check_output(cmd, shell=True)

assert EXPECT in result
