#!/usr/bin/env sh
#
# Copyright 2016 LasLabs Inc.
# License MIT or later (https://opensource.org/licenses/MIT).

OUTPUT=`docker exec -i -t $DOCKER_CONTAINER_ID ps aux`

echo "Command in $DOCKER_CONTAINER_ID responded with:"
echo $OUTPUT

echo $OUTPUT | grep -q "This is definitely not a running program!"
