#!/usr/bin/env sh
#
# Copyright 2016 LasLabs Inc.
# License Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0.html).

OUTPUT=`docker exec -i -t $DOCKER_CONTAINER_ID ps aux`

echo "Command in $DOCKER_CONTAINER_ID responded with:"
echo $OUTPUT

echo $OUTPUT | grep -q "This is definitely not a running program!"
