#!/usr/bin/env bash
#
# Copyright 2016 LasLabs Inc.
# License MIT or later (https://opensource.org/licenses/MIT).

set -e

echo "Running After Install"

if [ "${LINT_CHECK}" = "1" ]; 
then

  . travis_after_success_lint

elif [ "${TESTS}" = "1" ]; 
then

  . travis_after_success_test

elif [ "${DOCS}" = "1" ]; 
then

  if [ "${TRAVIS_BRANCH}" = "${BRANCH_PROD:=master}" ] \
  && [ "${TRAVIS_PULL_REQUEST}" = "false" ];
  then

    . travis_after_success_doc

  fi

elif [ "${HUB}" = "1" ];
then

  if [ "${TRAVIS_BRANCH}" = "${BRANCH_PROD:=master}" ] \
  && [ "${TRAVIS_PULL_REQUEST}" = "false" ];
  then

    . travis_after_success_hub

  fi

fi
