#!/usr/bin/env bash
#
# Copyright 2016 LasLabs Inc.
# License Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0.html).

set -e

echo "Running Matrix Functions"

if [ "${LINT_CHECK}" = "1" ]; 
then

    travis_run_lint

elif [ "${TESTS}" = "1" ]; 
then

    travis_run_test

elif [ "${HUB}" = "1" ];
then

    if [ "${TRAVIS_BRANCH}" = "${BRANCH_PROD:=master}" ] \
    && [ "${TRAVIS_PULL_REQUEST}" = "false" ];
    then

        . travis_run_hub

    fi

fi
