#!/usr/bin/env bash
#
# Copyright 2016 LasLabs Inc.
# License Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0.html).

set -e

echo "Installing All Dependencies"

# Colored Logs
pip install coloredlogs

# Fix Cert errors
# pip install requests[security]

# Now do the independent actions
if [ "${LINT_CHECK}" = "1" ]; then

    . travis_install_lint

fi

if [ "${TESTS}" = "1" ]; then

    . travis_install_test

# Install already does this
elif [ "${HUB}" = "1" ]; then

    if [ "${TRAVIS_BRANCH}" = "${BRANCH_PROD:=master}" ] \
    && [ "${TRAVIS_PULL_REQUEST}" = "false" ];
    then

        . travis_install_hub

    fi

fi
