#!/usr/bin/env python
#
# Copyright 2016 LasLabs Inc.
# License Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0.html).

import logging
import os
import subprocess

import coloredlogs

coloredlogs.install(level='DEBUG')

build_dir = os.environ.get('TRAVIS_BUILD_DIR', './')
dockerfile = os.environ.get('DOCKERFILE', 'Dockerfile')
lint_ignore = os.environ.get('LINT_IGNORE', [])

docker_build_dir = os.environ.get('DOCKER_DIR', '')
docker_build_dir = os.path.join(
    build_dir, docker_build_dir,
)

if lint_ignore:
    lint_ignore = lint_ignore.split(',')

dockerfile_path = os.path.abspath(
    os.path.join(docker_build_dir, dockerfile),
)

cmd = ['docker', 'run', '--rm', '-i', 'lukasmartinelli/hadolint',
       'hadolint']

for ignore in lint_ignore:
    cmd.extend(('--ignore', ignore))

cmd.extend(['-', '<', '"%s"' % dockerfile_path])

process = subprocess.Popen(
  ' '.join(cmd), shell=True, stdout=subprocess.PIPE, env=os.environ.copy(),
)

while True:
    output = process.stdout.readline()
    if output == '' and process.poll() is not None:
        break
    if output:
        logging.debug(output.strip())
    process.poll()

exit(process.returncode)
