#!/usr/bin/env bash
#
# Copyright 2016 LasLabs Inc.
# License MIT or later (https://opensource.org/licenses/MIT).

set -e

echo "Installing All Dependencies"

# Colored Logs
pip install coloredlogs

# Fix Cert errors
# pip install requests[security]

# Now do the independent actions
if [ "${LINT_CHECK}" = "1" ]; 
then

    . travis_install_lint

elif [ "${TESTS}" = "1" ]; 
then

    . travis_install_test

elif [ "${HUB}" = "1" ];
then

    if [ "${TRAVIS_BRANCH}" = "${BRANCH_PROD:=master}" ] \
    && [ "${TRAVIS_PULL_REQUEST}" = "false" ];
    then

        . travis_install_hub

    fi

fi
