#!/usr/bin/env bash
#
# Copyright 2016 LasLabs Inc.
# License Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0.html).

set -e

echo "Running After Install"

if [ "${LINT_CHECK}" = "1" ]; then

  . travis_after_success_lint

fi

if [ "${TESTS}" = "1" ]; then

  . travis_after_success_test

fi

if [ "${DOCS}" = "1" ]; then

  if [ "${TRAVIS_BRANCH}" = "${BRANCH_PROD:=master}" ] \
  && [ "${TRAVIS_PULL_REQUEST}" = "false" ];
  then

    . travis_after_success_doc

  fi

fi

if [ "${HUB}" = "1" ]; then

  if [ "${TRAVIS_BRANCH}" = "${BRANCH_PROD:=master}" ] \
  && [ "${TRAVIS_PULL_REQUEST}" = "false" ];
  then

    . travis_after_success_hub

  fi

fi
